import React from "react"

export const About = React.lazy(() => import("./About"))
export const Billing = React.lazy(() => import("./Billing"))
export const Blog = React.lazy(() => import("./Blog"))
export const Blogs = React.lazy(() => import("./Blogs"))
export const Book = React.lazy(() => import("./Book"))
export const Contact = React.lazy(() => import("./Contact"))
export const Course = React.lazy(() => import("./Course"))
export const Courses = React.lazy(() => import("./Courses"))
export const Home = React.lazy(() => import("./Home"))
export const Inbox = React.lazy(() => import("./Inbox"))
export const Learning = React.lazy(() => import("./Learning"))
export const Library = React.lazy(() => import("./Library"))
export const Notifications = React.lazy(() => import("./Notifications"))
export const ResetPassword = React.lazy(() => import("./ResetPassword"))
export const Settings = React.lazy(() => import("./Settings"))
export const Signin = React.lazy(() => import("./Signin"))
export const Signup = React.lazy(() => import("./Signup"))
export const Track = React.lazy(() => import("./Track"))
export const Tracks = React.lazy(() => import("./Tracks"))
